// create a volunteer

POST http://localhost:8080/users

Content-Type: application/json

{
    "name" : "atharv",
    "email": "tester1@gmail.com",
    "password": "123456",
    "confPassword":"123456",
    "role" : "admin"

}